//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuanGenerate {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MySqlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MySqlResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuanGenerate.MySqlResource", typeof(MySqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT  
        ///TABLE_NAME as TableName,
        ///COLUMN_NAME AS FieldName ,
        ///DATA_TYPE   AS DataType, CASE WHEN  POSITION( &apos;unsigned&apos;IN COLUMN_TYPE)&gt;0
        /// THEN 1 ELSE 0 END AS IsUnsigned,
        ///COLUMN_COMMENT as Description,
        ///CASE WHEN IS_NULLABLE =&apos;YES&apos; 
        /// THEN 1 ELSE 0 END   as IsNullable,
        ///CASE WHEN COLUMN_KEY =&apos;PRI&apos; 
        /// THEN 1 ELSE 0 END   as IsKey,
        ///
        /// 
        /// CASE WHEN EXTRA =&apos;auto_increment&apos;
        ///  
        /// THEN 1 ELSE 0 END AS Identity,
        ///
        ///CASE WHEN CHARACTER_MAXIMUM_LENGTH is not NULL
        ///  
        /// THEN CHARACTER_MAXIMUM_LENGTH
        /// 
        /// ELSE 0 E [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string GetTableColumns {
            get {
                return ResourceManager.GetString("GetTableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT
        ///  CONSTRAINT_CATALOG,
        ///  CONSTRAINT_SCHEMA,
        ///  CONSTRAINT_NAME ,
        ///  TABLE_CATALOG,
        ///  TABLE_SCHEMA,
        ///  TABLE_NAME  as PrimaryTableName,
        ///  COLUMN_NAME as PrimaryColumnName,
        ///  ORDINAL_POSITION,
        ///  POSITION_IN_UNIQUE_CONSTRAINT,
        ///  REFERENCED_TABLE_SCHEMA,
        ///  REFERENCED_TABLE_NAME as ForeignTableName,
        ///  REFERENCED_COLUMN_NAME as ForeignColumnName
        ///FROM information_schema.KEY_COLUMN_USAGE where table_name=?TableName
        ///  and  CONSTRAINT_SCHEMA=?TableSchema  and REFERENCED_COLUMN_NAME is not  null 的本地化字符串。
        /// </summary>
        internal static string GetTableForeign {
            get {
                return ResourceManager.GetString("GetTableForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT
        ///  TABLE_CATALOG,
        ///  TABLE_SCHEMA,
        ///  TABLE_NAME as TableName,
        ///  TABLE_TYPE,
        ///  ENGINE,
        ///  VERSION,
        ///  ROW_FORMAT,
        ///  TABLE_ROWS,
        ///  AVG_ROW_LENGTH,
        ///  DATA_LENGTH,
        ///  MAX_DATA_LENGTH,
        ///  INDEX_LENGTH,
        ///  DATA_FREE,
        ///  AUTO_INCREMENT,
        ///  CREATE_TIME,
        ///  UPDATE_TIME,
        ///  CHECK_TIME,
        ///  TABLE_COLLATION,
        ///  CHECKSUM,
        ///  CREATE_OPTIONS,
        ///  TABLE_COMMENT as Description 
        ///FROM information_schema.TABLES  where TABLE_TYPE=?TableType and  TABLE_SCHEMA=?TableSchema 的本地化字符串。
        /// </summary>
        internal static string GetTables {
            get {
                return ResourceManager.GetString("GetTables", resourceCulture);
            }
        }
    }
}
