
CREATE TABLE `bizhi_esignuserinfo_tb` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `GUID` VARCHAR(36) DEFAULT '' COMMENT 'GUID',
  `UserID` INT(11) DEFAULT '0' COMMENT 'UserID',
  `Phone` VARCHAR(20) DEFAULT '' COMMENT 'Phone',
  `UserName` VARCHAR(20) DEFAULT '' COMMENT '用户名称',
  `UserIDCard` VARCHAR(50) DEFAULT '' COMMENT '身份证号码',
  `PsnID` VARCHAR(20) DEFAULT '' COMMENT 'PsnID',
  `AuthFlowId` VARCHAR(50) DEFAULT '' COMMENT 'AuthFlowId',
  `AuthUrl` VARCHAR(300) DEFAULT '' COMMENT '身份证号码',
  `CreateTime` DATETIME NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '添加时间',
  `ModifyTime` DATETIME NOT NULL DEFAULT '1900-01-01 00:00:00' COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  KEY `GUID` (`GUID`),
  UNIQUE KEY `UserID` (`UserID`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='e签宝个人认证信息'
