CREATE TABLE `log_application_tb` (
  `ApplicationID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '程序标识',
  `ApplicationCode` VARCHAR(100) NOT NULL COMMENT '程序代码',
  `ApplicationName` VARCHAR(100) NOT NULL COMMENT '程序名称',
  `ParentID` INT(11) NOT NULL COMMENT '父标识',
  `IDPath` VARCHAR(100) NOT NULL COMMENT '父路经',
  `SortIndex` INT(11) NOT NULL COMMENT '排序',
  `CreateDate` DATETIME NOT NULL COMMENT '创建时间',
  `NoticeCheckInfo` VARCHAR(1000) NOT NULL COMMENT '日志通知检查',
  `LogStoreInfo` VARCHAR(1000) NOT NULL COMMENT '日志存储信息',
  `NoticePhone` VARCHAR(200) NOT NULL COMMENT '通知手机号码',
  `NoticeInterval` INT(11) NOT NULL DEFAULT '10' COMMENT '通知间隔分钟数',
  `IsNotice` INT(11) NOT NULL DEFAULT '0' COMMENT '是否通知',
  `HeaderKey` VARCHAR(100) NOT NULL COMMENT '头部键值',
  `FormKey` VARCHAR(100) NOT NULL COMMENT 'Form键值',
  `CookieKey` VARCHAR(100) NOT NULL COMMENT 'Cookie键值',
  PRIMARY KEY (`ApplicationID`),
  KEY `ApplicationCode` (`ApplicationCode`)
) ENGINE=INNODB  DEFAULT CHARSET=utf8 COMMENT='日志程序表'

CREATE TABLE `log_logdata_tb` (
  `LogID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '日志标识',
  `ApplicationID` INT(11) NOT NULL COMMENT '程序标识',
  `ApplicationName` VARCHAR(100) NOT NULL COMMENT '程序名称',
  `ApplicationHost` VARCHAR(50) NOT NULL COMMENT '运行程序名称',
  `CurrentThreadID` VARCHAR(32) NOT NULL COMMENT '当前线程标识',
  `Url` VARCHAR(1000) NOT NULL COMMENT '当前地址',
  `UrlReferrer` VARCHAR(1000) NOT NULL COMMENT '上一次地址',
  `UserAgent` VARCHAR(3000) NOT NULL DEFAULT '' COMMENT 'UserAgent信息',
  `UserID` VARCHAR(100) NOT NULL COMMENT '用户标识',
  `UserIP` VARCHAR(30) NOT NULL COMMENT '用户IP',
  `ProcessName` VARCHAR(500) NOT NULL COMMENT '处理名称',
  `CreateDate` DATETIME NOT NULL COMMENT '创建时间',
  `LogDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '日志时间',
  `Title` VARCHAR(1000) NOT NULL COMMENT '标题',
  `Message` LONGTEXT NOT NULL COMMENT '日志消息',
  `ResultMessage` LONGTEXT NOT NULL COMMENT '结果消息',
  `LogType` VARCHAR(20) NOT NULL COMMENT '日志类型',
  `IDPath` VARCHAR(100) NOT NULL COMMENT '路经',
  `HeadersData` LONGTEXT NOT NULL COMMENT '头部信息',
  `FormData` LONGTEXT NOT NULL COMMENT 'Post信息',
  `CookiesData` TEXT NOT NULL COMMENT 'Cookie信息',
  `MessageID` VARCHAR(100) NOT NULL COMMENT '消息标识',
  `DeviceID` VARCHAR(100) NOT NULL COMMENT '设备标识',
  PRIMARY KEY (`LogID`),
  KEY `IDPath` (`IDPath`),
  KEY `LogType` (`LogType`),
  KEY `Notify` (`ApplicationID`,`LogType`,`LogDate`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='日志数据表'
